### PR TITLE
JSON Support for plugins

### PR DESCRIPTION
**Pull request by educatalan02**
UseJsonForPlugins bool at Rocket.Config.xml 

Now you can add comments to the JSON config file
Code:
`[JsonConverter(typeof(JsonExtension), "Name")]
public string Name = "test";`
Result:
`{
  "Name": "test"/*Name*/,
}`

### CODE REVIEW

**Comment by mkspeed0** [comment]
Hi! The idea is very good and was considered by me the other day. First of all, you should open an Issue with this topic and find out the opinion of others. Then publish a Pull Request. So another erroneous point, do not close your pull requests as well as issues. Sunnamed434 closes the pull request itself, doing so by publishing.

**Comment by educatalan02** [comment]
Purpose of this is to discuss It here, no matter if its an issue or not. I closed the pr because I forgot to removed unused Code.

**Review by sunnamed434 — APPROVED** [review]
Looks good to me

**Comment by sunnamed434** [comment]
Please make another PR or bump the latest updates from the master branch of this repo, because this one has conflicts due to an outdated branch

**Pull request closed without merging**
