### PR TITLE
Change rocket command output by RocketModFix

### LINKED ISSUE #17: Update command /rocket
Now `/rocket` outputs:
```console
Rocket v0.0.0.0 for Unturned v3.23.12.3
https://rocketmod.net - 2017
```

Instead, add more info about the fork, change `https://rocketmod.net` to the GitHub repo, and maybe add a Discord invite URL

### PR DESCRIPTION
**Pull request by nazmiyigitefe**
Fixes #17

### CODE REVIEW

**Comment by sunnamed434** [comment]
Next time make sure to make branch from dev instead of master

**Comment by nazmiyigitefe** [comment]
Got it, didn't saw it

**Comment by sunnamed434** [comment]
Next time finish the task you've started, otherwise close PR

**Comment by sunnamed434** [comment]
> Next time finish the task you've started, otherwise close PR

Sorry for my mistake, I didn't submit the Code Review :P
image

**Pull request merged**
